### ISSUE TITLE
Preview on renamed assets no longer works

### ISSUE THREAD

**Issue by blacksaltstudio** [glue-agency/craft-fingerprint-assets#1]
After applying a crop the image correctly got the new filename but it no longer allows me to 'preview' the image from Assets. 

Is this because of the . added to the filename?

**Comment by jorenvanhee** [comment]
I can't seem to reproduce it. Can you put your exact steps and Craft version here?

**Comment by blacksaltstudio** [comment]
In Assets I select the image and choose EDIT, I gave it a slight crop and on save it automatically updates the image URL with a .string (which is what the plugin should do), then i select the checkbox next to the image and the Preview is greyed out (disabled). 

I am running on a Rackspace Cloud Server than uses the Rackspace Cloudfiles for images. Could that potentially be the issue?

**Comment by jorenvanhee** [comment]
Could be related. I don't have access to Rackspace Cloudfiles, but I'll try to replicate it with an Amazon S3 volume.

**Comment by jorenvanhee** [comment]
Everything seems to work here with a S3 volume. Do you also have the issue with local volumes?

You could maybe try this to narrow down the problem:
- Uninstall the plugin
- Crop the image and rename it manually (in the Rackspace volume)

**Comment by blacksaltstudio** [comment]
I cropped it then renamed the image manually with two '.' in there and it seemed to work. 

http://69b6f8fd736ed8836881-2f84b28f704f9f5fbcd9c873e843c0af.r11.cf1.rackcdn.com/images/entries/jakePhelpsRIP-test.testing.fgeyufgwe.jpg

This is with the plugin uninstalled

**Comment by jorenvanhee** [comment]
I'll close this issue for now. I cannot replicate it without a Rackspace volume. Feel free to send me a working project with Rackspace, or a PR. Also, I saw this on the Craft Rackspace github page:

> Rackspace is no longer maintaining their PHP OpenCloud SDK, so you should probably find a different asset storage provider and not use this plugin.
